### ISSUE TITLE
Site release cant be triggered - lutaml.org

### ISSUE THREAD

**Issue by w00lf** [riboseinc/react-static-plugin-aperis-doc-pages#6]
@strogonoff can you please help with the new release of https://github.com/lutaml/lutaml.org?

**Comment by ronaldtse** [comment]
I think Aperis could support (temporarily) a manual GHA workflow so that we can get deploying soon?

**Comment by strogonoff** [comment]
I recommend using manual YAML workflow for a little while, if you are comfortable with it. I can take a look at this config in a bit if needed

**Comment by ronaldtse** [comment]
It's fine to use the manual YAML workflow but right now Aperis/Paneron removes it? Can we have Aperis/Paneron not remove the existing workflows?

**Comment by strogonoff** [comment]
During conversion of a legacy repository (created with pre alpha19) to multi-dataset repository format, Paneron moves everything under dataset directory. This includes CI workflows, since Paneron can’t know exactly what CI workflows do and they will typically break if left as is. 

That is a one-time process only applicable to legacy repositories created in pre-alpha19 Paneron for which user chooses to run automated migration

This is not the only issue with automated migration. For that reason I recommend to not run automigration and leave it to me instead to ensure it works and fix CI. 

Outside that one-time action, *a manually specified CI configuration should not get removed by Paneron* (if it does, that’s a bug that should be filed separately).

**Comment by ronaldtse** [comment]
I have manually added back the GHA workflows to https://github.com/lutaml/lutaml.org/commit/93d28e0e392a1aad11ab3193f171d80ddd1ccf5c

**Comment by ronaldtse** [comment]
lutaml.org deployment works. Closing.
